# Generated by Django 2.0.5 on 2019-02-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
